images:
  image:
    repository: ghcr.io/hypetek/hypetek-gamevault
    tag: 0.9.0-rc.5
  translator_image:
    repository: libretranslate/libretranslate
    tag: v1.9.6
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  app_container_name: mission-control
  translator_container_name: translator
  perms_container_name: permissions
  web_port: 8080
  app_uid: 568
  app_gid: 568
  translator_uid: 1032
  translator_gid: 65534
